- platform: xiaomi_miio
  host: 192.168.50.240
  token: !secret token_nawilzacz
  name: Nawilzacz
  model: zhimi.humidifier.cb1
- platform: xiaomi_miio
  host: 192.168.50.85
  token: !secret token_oczyszczacz
  name: Oczyszczacz
  model: zhimi.airpurifier.m2