title: Dom
theme: default


resources: !include lovelace/resources.yaml
#custom_header: !include lovelace/custom_header.yaml

views: !include lovelace/views/views.yaml
#  - title: Dom
#    badges:
#      - entity: binary_sensor.updater
#      - entity: sun.sun
#    icon: mdi:home-assistant
#    cards:
#      - type: 'custom:weather-card'
#        title: Weather
#        entity: weather.dark_sky
#        icons: '/local/custom-lovelace/weather-card/icons/'
#      - type: map
#        entities:
#          - entity: zone.home
#          - entity: zone.praca_artur
#          - entity: zone.praca_kasia
#          - entity: device_tracker.hd1910
#          - entity: device_tracker.redmi_note_8_pro
#      - type: entities
#        title: Weather
#        show_header_toggle: false
#        entities:
#          - sensor.dark_sky_summaryzone
#          - sensor.pollen_level
#          - sensor.cold_flu_risk
#          - sensor.dark_sky_hourly_summary
#          - sensor.dark_sky_daily_summary
# Sypialnia
#  - title: Sypialnia
#    icon: mdi:sofa
#    badges:
#      - entity: weather.dark_sky
#    cards:
#      - type: map
#        entities:
#          - entity: device_tracker.hd1910
#          - entity: zone.home
#          - entity: zone.praca_artur
#          - entity: zone.praca_kasia
#    #Salon
#  - title: Sypialnia
#    icon: mdi:sofa
#    badges:
#      - entity: weather.dark_sky
#    cards:
#      - type: entities
#        title: Oczyszczacz
#        entities:
#          - entity: fan.oczyszczacz
#          - entity: input_select.oczyszczacz_mode
#          - entity: input_number.oczyszczacz_favorite_level
#          - entity: switch.xiaomi_airpurifier_child_lock
#          - entity: switch.xiaomi_airpurifier_led
#          - entity: switch.xiaomi_airpurifier_buzzer
#          - entity: sensor.xiaomi_airpurifier_speed
#          - entity: sensor.xiaomi_airpurifier_filter_remaining
#          - entity: sensor.xiaomi_airpurifie_hours_used
#          - entity: sensor.xiaomi_airpurifie_fan_mode
#        show_header_toggle: false
#        theme: default
#      - entities:
#          - entity: sensor.xiaomi_airpurifier_air_quality_pm25
#          - entity: sensor.xiaomi_airpurifier_temp
#            icon: mdi:temperature-celsius
#          - entity: sensor.xiaomi_airpurifier_humidity
#        show_header_toggle: false
#        theme: default
#        title: Environment
#        type: entities
#      - entities:
#        - sensor.xiaomi_airpurifier_air_quality_pm25
#        hours_to_show: 80
#        refresh_interval: 60
#        title: Air quality
#        type: history-graph
#    #Osoby
#  - title: Osoby
#    icon: mdi:human-male-female
#    badges:
#      - entity: person.artur
#      - entity: device_tracker.hd1910
#      - entity: sensor.oneplus7tpro_battery_level
#      - entity: person.kasia
#      - entity: device_tracker.redmi_note_8_pro
#      - entity: sensor.redmi_note_8_pro_battery_level
#    cards:
#      - type: entities
#        title: Internet
#        entities:
#          - device_tracker.hd1910
#          - sensor.hd1910_wifi_connection
#          - device_tracker.redmi_note_8_pro
#          - sensor.redmi_note_8_pro_wifi_connection
#      - type: entities
#        title: Bateria
#        entities: 
#          - sensor.oneplus7tpro_battery_level
#          - sensor.redmi_note_8_pro_battery_level
#      - type: entities
#        title: Lokalizacja
#        entities: 
#          - sensor.hd1910_geocoded_location
#          - sensor.redmi_note_8_pro_geocoded_location
##Oczyszczacz
#  - title: Oczyszczacz
##    icon: mdi:human-male-female
##    badges:
#    cards:
#      - elements:
#        - entity: fan.oczyszczacz
#          style:
#            '--iron-icon-height': 45px
#            '--iron-icon-width': 45px
#            margin-right: '-10%'
#            right: 16%
#            top: 85%
#          tap_action:
#            action: call-service
#            service: fan.toggle
#            service_data:
#              entity_id: fan.oczyszczacz
#          type: state-icon
#        - icon: 'mdi:water-percent'
#          style:
#            '--iron-icon-height': 45px
#            '--iron-icon-width': 45px
#            color: dodgerblue
#            left: 15%
#            top: 25%
#          tap_action: none
#          type: icon
#        - attribute: humidity
#          color_stops: null
#          entity: fan.oczyszczacz
#          fill: 'rgba(0,0,0,0.3)'
#          font_style:
#            color: white
#          gradient: true
#          max: 100
#          min: 0
#          show_card: null
#          stroke_width: 10
#          style:
#            height: 60px
#            left: 15%
#            top: 25%
#            width: 60px
#          type: 'custom:circle-sensor-card'
#          units: '%'
#        - icon: 'mdi:thermometer'
#          style:
#            '--iron-icon-height': 45px
#            '--iron-icon-width': 45px
#            color: dodgerblue
#            left: 15%
#            top: 45%
#          tap_action: none
#          type: icon
#        - attribute: temperature
#          entity: fan.oczyszczacz
#          fill: 'rgba(0,0,0,0.3)'
#          font_style:
#            color: white
#          gradient: true
#          max: 50
#          min: 0
#          show_card: false
#          stroke_width: 10
#          style:
#            height: 60px
#            left: 15%
#            top: 45%
#            width: 60px
#          type: 'custom:circle-sensor-card'
#          units: °C
#        - icon: 'mdi:air-filter'
#          style:
#            '--iron-icon-height': 45px
#            '--iron-icon-width': 45px
#            color: dodgerblue
#            left: 15%
#            top: 65%
#          tap_action: none
#          type: icon
#        - attribute: aqi
#          entity: fan.oczyszczacz
#          fill: 'rgba(0,0,0,0.3)'
#          font_style:
#            color: white
#          gradient: true
#          max: 70
#          min: 0
#          show_card: false
#          stroke_width: 10
#          style:
#            height: 60px
#            left: 15%
#            top: 65%
#            width: 60px
#          type: 'custom:circle-sensor-card'
#          units: ''
#        - icon: 'mdi:speedometer'
#          style:
#            '--iron-icon-height': 45px
#            '--iron-icon-width': 45px
#            color: dodgerblue
#            left: 15%
#            top: 85%
#          tap_action: none
#          type: icon
#        - attribute: motor_speed
#          entity: fan.oczyszczacz
#          fill: 'rgba(0,0,0,0.3)'
#          font_style:
#            color: white
#          gradient: true
#          max: 2000
#          min: 0
#          show_card: false
#          stroke_width: 10
#          style:
#            height: 60px
#            left: 15%
#            top: 85%
#            width: 60px
#          type: 'custom:circle-sensor-card'
#          units: ''
#        - entity: sensor.xiaomi_airpurifie_fan_mode
#          max: 2000
#          min: 0
#          prefix: 'Tryb: '
#          style:
#            background-color: 'rgba(0, 0, 0,.0)'
#            border-color: 'rgb(34, 154, 210,.0)'
#            border-left-style: solid
#            color: 'rgba(255, 255, 255,)'
#            font-family: Trebuchet MS
#            font-size: 100%
#            font-weight: bold
#            left: 85%
#            margin-right: '-50%'
#            opacity: 1
#            pointer-events: none
##            text-shadow: 1px 1px black
#            top: 5%
#            transform: 'translate(-50%,-0%)'
#          type: state-label
#        - icon: 'mdi:brightness-auto'
#          style:
#            '--iron-icon-height': 45px
#            '--iron-icon-width': 45px
#            right: 5%
#            top: 25%
#          tap_action:
#            action: call-service
#            service: fan.set_speed
#            service_data:
#              entity_id: fan.oczyszczacz
#              speed: Auto
#          type: icon
#        - icon: 'mdi:power-sleep'
#          style:
#            '--iron-icon-height': 45px
#            '--iron-icon-width': 45px
#            right: 5%
#            top: 45%
#          tap_action:
#            action: call-service
#            service: fan.set_speed
#            service_data:
#              entity_id: fan.oczyszczacz
#              speed: Silent
#          type: icon
#        - icon: 'mdi:account-heart'
#          style:
#            '--iron-icon-height': 45px
#            '--iron-icon-width': 45px
#            right: 5%
#            top: 65%
#          tap_action:
#            action: call-service
#            service: fan.set_speed
#            service_data:
#              entity_id: fan.oczyszczacz
#              speed: Favorite
#          type: icon
#        - entity: sensor.xiaomi_airpurifier_filter_remaining
#          prefix: 'Filtr: '
#          style:
#            background-color: 'rgba(0, 0, 0,.0)'
#            border-color: 'rgb(34, 154, 210,.0)'
#            border-left-style: solid
#            color: dodgerblue
#            font-family: Trebuchet MS
#            font-size: 100%
#            font-weight: bold
#            left: 2%
#            opacity: 1
#            pointer-events: none
#            top: 10%
#            transform: 'translate(0%,-50%)'
#          type: state-label
#        - entity: sensor.xiaomi_airpurifie_hours_used
#          prefix: 'Działa: '
#          style:
#            background-color: 'rgba(0, 0, 0,.0)'
#            border-color: 'rgb(34, 154, 210,.0)'
#            border-left-style: solid
#            color: dodgerblue
#            font-family: Trebuchet MS
#            font-size: 100%
#            font-weight: bold
#            left: 2%
#            margin-right: '-50%'
#            opacity: 1
#            pointer-events: none
#            top: 5%
#            transform: 'translate(0%,-50%)'
#          type: state-label
#        image: /local/pictures/oczyszczacz.png
#        type: picture-elements
#    type: 'custom:vertical-stack-in-card'
#style:
#  background-color: 'rgba(0,0,20,0.3)'
#  background-image: url("/local/pictures/cardback.png")
#  background-repeat: no-repeat
#  background-size: 100% 100%
#  border: 'solid 1px rgba(57,128,228,0.4)'
#  border-radius: 20px
#type: 'custom:card-modder'